/**
 * What the classic Prompt Studio app (apps/prompt-studio) takes from Castcut's routes: every page,
 * API route and special file outside the Play layer, as a wrapper that re-exports it. Pure; used
 * by scripts/gen-classic-app.mts and its test. docs/architecture-boundaries.md.
 */
import { isPlayLayer } from './architecture-boundaries';

export const CLASSIC_APP_DIR = 'apps/prompt-studio';
export const CLASSIC_GENERATED_MARK = '// Generated by scripts/gen-classic-app.mts';

/** Written by hand in the classic app (its own layout and styles). */
const CLASSIC_OWN = new Set(['src/app/layout.tsx', 'src/app/globals.css', 'src/app/favicon.ico']);

export function classicAppFiles(appFiles: readonly string[], owned: ReadonlySet<string>): string[] {
  return appFiles
    .filter(path => /\.(?:ts|tsx)$/.test(path) && !/\.test\.(?:ts|tsx)$/.test(path))
    .filter(path => !CLASSIC_OWN.has(path) && !isPlayLayer(path, owned))
    .sort();
}

/** Segment config Next reads statically: copied as written (single-line `export const`). */
const SEGMENT_CONFIG_RE =
  /^export const (?:runtime|maxDuration|dynamic|revalidate|fetchCache|dynamicParams|preferredRegion|size|contentType|alt)\b[^\n]*;$/gm;

/** The proxy's `config` (matcher) block. */
const PROXY_CONFIG_RE = /^export const config = \{[\s\S]*?\n\};$/m;

export function wrapperSource(sourcePath: string, source: string): string {
  const spec = '@/' + sourcePath.replace(/^src\//, '').replace(/\.(?:ts|tsx)$/, '');
  const client = /^\s*['"]use client['"]/.test(source);
  const hasDefault = /^export default\b/m.test(source);
  const lines = [CLASSIC_GENERATED_MARK + ` from ${sourcePath} — do not edit.`];
  if (client) {
    // A client module can only be re-exported by name.
    lines.unshift("'use client';", '');
    if (hasDefault) lines.push(`export { default } from '${spec}';`);
    return lines.join('\n') + '\n';
  }
  const config = [...source.matchAll(SEGMENT_CONFIG_RE)].map(match => match[0]);
  const proxyConfig = PROXY_CONFIG_RE.exec(source)?.[0];
  if (proxyConfig) config.push(proxyConfig);
  lines.push(...config);
  if (proxyConfig) {
    // Next looks for a `proxy` function declared in the file itself.
    lines.push(
      "import type { NextRequest } from 'next/server';",
      `import { proxy as sharedProxy } from '${spec}';`,
      'export function proxy(request: NextRequest) {',
      '  return sharedProxy(request);',
      '}'
    );
    return lines.join('\n') + '\n';
  }
  lines.push(`export * from '${spec}';`);
  if (hasDefault) lines.push(`export { default } from '${spec}';`);
  return lines.join('\n') + '\n';
}
