/**
 * Player-facing names for pose-guide layouts, and the groups the "Change pose" picker shows.
 * Ids are the pose guide's (`SocialLayout`, `PoseGuideBase`, intimate layouts).
 */

const LABELS: Record<string, string> = {
  // Postures
  stand: 'Standing',
  walk: 'Walking',
  run: 'Running',
  sit: 'Sitting',
  crouch: 'Crouching',
  kneel: 'Kneeling',
  reach: 'Reaching',
  lean: 'Leaning',
  lie: 'Lying down',
  jump: 'Jumping',
  // Everyday
  phone: 'On the phone',
  drink: 'Drink in hand',
  read: 'Reading',
  carry: 'Carrying a bag',
  wave: 'Waving',
  point: 'Pointing',
  pockets: 'Hands in pockets',
  cross_arms: 'Arms crossed',
  hands_hips: 'Hands on hips',
  hair_touch: 'Touching hair',
  shrug: 'Shrugging',
  look_back: 'Looking back',
  stretch: 'Stretching',
  lean_wall: 'Leaning on a wall',
  rail: 'At a rail',
  foot_up: 'Foot up on a step',
  bend_pick: 'Bending to pick up',
  stairs: 'On the stairs',
  climb: 'Climbing',
  sit_floor: 'Cross-legged on the floor',
  lounge_elbows: 'Lounging on elbows',
  lie_front: 'Lying on the front',
  lie_side: 'Lying on the side',
  perch_edge: 'Perched on an edge',
  hands_behind_head: 'Hands behind head',
  arms_up: 'Arms up',
  selfie: 'Selfie',
  photograph: 'Taking a photo',
  cook: 'Cooking',
  laptop: 'On a laptop',
  eat: 'Eating',
  // Not in the picker: a pose read from the player's own photo.
  photo: 'Your photo pose',
  // Two people
  hug: 'Hug',
  dance: 'Dancing',
  fight: 'Sparring',
  hold_hands: 'Holding hands',
  piggyback: 'Piggyback',
  high_five: 'High five',
  toast: 'Toast',
  head_shoulder: 'Head on a shoulder',
  selfie_duo: 'Selfie together',
  // Sport
  sport_sprint: 'Sprint',
  sport_yoga_warrior: 'Yoga warrior',
  sport_yoga_dog: 'Downward dog',
  sport_cycle: 'Cycling',
  sport_swing: 'Golf swing',
  sport_serve: 'Tennis serve',
  sport_forehand: 'Forehand',
  sport_jump_shot: 'Jump shot',
  sport_kick: 'Kick',
  sport_throw: 'Throw',
  sport_lunge: 'Lunge',
  sport_handstand: 'Handstand',
  sport_pitch: 'Pitch',
  sport_stick: 'Stick handling',
  sport_block: 'Block',
  sport_hurdle: 'Hurdle',
  sport_slide: 'Slide',
  sport_dunk: 'Dunk',
  sport_ski: 'Skiing',
  sport_putt: 'Putt',
  sport_overhead: 'Overhead smash',
  sport_swim: 'Swimming',
  sport_spike: 'Spike',
  sport_box: 'Boxing',
  sport_surf: 'Surfing',
  sport_squat: 'Squat',
  sport_deadlift: 'Deadlift',
  sport_pushup: 'Push-up',
  sport_plank: 'Plank',
  sport_pullup: 'Pull-up',
  sport_skate: 'Skateboarding',
};

/** Player-facing name for any pose-guide layout id. */
export function poseLayoutLabel(id: string | null | undefined): string {
  const key = id?.trim();
  if (!key) return 'Auto';
  return (
    LABELS[key] ??
    key
      .replace(/^sport_/, '')
      .replace(/_/g, ' ')
      .replace(/^\w/, c => c.toUpperCase())
  );
}

export type PosePickerGroup = { label: string; ids: readonly string[] };

/** "Change pose" menu groups. Two-person poses only draw two figures with Duo on. */
export const POSE_PICKER_GROUPS: readonly PosePickerGroup[] = [
  {
    label: 'Postures',
    ids: ['stand', 'walk', 'run', 'sit', 'crouch', 'kneel', 'reach', 'lean', 'lie', 'jump'],
  },
  {
    label: 'Everyday',
    ids: [
      'phone',
      'drink',
      'read',
      'carry',
      'wave',
      'point',
      'pockets',
      'cross_arms',
      'hands_hips',
      'hair_touch',
      'shrug',
      'look_back',
      'stretch',
      'lean_wall',
      'rail',
      'foot_up',
      'bend_pick',
      'stairs',
      'climb',
      'sit_floor',
      'lounge_elbows',
      'lie_front',
      'lie_side',
      'perch_edge',
      'hands_behind_head',
      'arms_up',
      'selfie',
      'photograph',
      'cook',
      'laptop',
      'eat',
    ],
  },
  {
    label: 'Two people',
    ids: [
      'hug',
      'dance',
      'fight',
      'hold_hands',
      'piggyback',
      'high_five',
      'toast',
      'head_shoulder',
      'selfie_duo',
    ],
  },
  {
    label: 'Sport',
    ids: [
      'sport_sprint',
      'sport_yoga_warrior',
      'sport_yoga_dog',
      'sport_cycle',
      'sport_swing',
      'sport_serve',
      'sport_forehand',
      'sport_jump_shot',
      'sport_kick',
      'sport_throw',
      'sport_lunge',
      'sport_handstand',
      'sport_pitch',
      'sport_stick',
      'sport_block',
      'sport_hurdle',
      'sport_slide',
      'sport_dunk',
      'sport_ski',
      'sport_putt',
      'sport_overhead',
      'sport_swim',
      'sport_spike',
      'sport_box',
      'sport_surf',
      'sport_squat',
      'sport_deadlift',
      'sport_pushup',
      'sport_plank',
      'sport_pullup',
      'sport_skate',
    ],
  },
];
