// Generated by scripts/gen-classic-app.mts from src/app/api/fal/status/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 60;
export * from '@/app/api/fal/status/route';
