// Generated by scripts/gen-classic-app.mts from src/studio-app/background/page.tsx — do not edit.
export * from '@/studio-app/background/page';
export { default } from '@/studio-app/background/page';
