// Generated by scripts/gen-classic-app.mts from src/app/api/diffusers/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 90;
export * from '@/app/api/diffusers/route';
