// Generated by scripts/gen-classic-app.mts from src/studio-app/workflow-editor/page.tsx — do not edit.
export * from '@/studio-app/workflow-editor/page';
export { default } from '@/studio-app/workflow-editor/page';
