#!/usr/bin/env python3
"""Turn the harvest manifest into what the app and the docs use:

  src/lib/data/pose-references.json   skeletons + credit, no photos (committed)
  docs/pose-reference-credits.md      one line per reference (committed)
  <cache>/sheets/sheet-NN.jpg         contact sheets: each kept crop with its skeleton drawn
  <cache>/report.txt                  counts per pose (kept / searched / rejected by reason)
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import cv2
import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))

from sources import ALLOWED_LICENCES  # noqa: E402

CACHE = Path(os.environ.get("POSE_REFS_CACHE", Path.home() / ".cache" / "castcut-pose-refs"))
DATA = ROOT / "src" / "lib" / "data" / "pose-references.json"
CREDITS = ROOT / "docs" / "pose-reference-credits.md"

LICENCE_NAMES = {"cc0": "CC0", "pdm": "Public Domain Mark", "by": "CC BY", "by-sa": "CC BY-SA"}

# OpenPose limb pairs and colours (BGR), as the guide draws them.
LIMBS = [(1, 2), (1, 5), (2, 3), (3, 4), (5, 6), (6, 7), (1, 8), (8, 9), (9, 10), (1, 11),
         (11, 12), (12, 13), (1, 0), (0, 14), (14, 16), (0, 15), (15, 17)]
COLOURS = [(0, 0, 255), (0, 85, 255), (0, 170, 255), (0, 255, 255), (0, 255, 170), (0, 255, 85),
           (0, 255, 0), (85, 255, 0), (170, 255, 0), (255, 255, 0), (255, 170, 0), (255, 85, 0),
           (255, 0, 0), (255, 0, 85), (255, 0, 170), (255, 0, 255), (170, 0, 255)]


def credit_of(ref: dict) -> dict:
    photo = ref["photo"]
    credit = {
        "title": photo["title"].strip() or "Untitled",
        "creator": photo["creator"].strip() or "Unknown",
        "licence": photo["licence"],
        "licenceVersion": photo["licence_version"],
        "licenceUrl": photo["licence_url"],
        "source": photo["landing_url"],
        "provider": photo["provider"],
    }
    if photo.get("creator_url"):
        credit["creatorUrl"] = photo["creator_url"]
    return credit


def licence_label(credit: dict) -> str:
    name = LICENCE_NAMES[credit["licence"]]
    version = credit.get("licenceVersion") or ""
    return f"{name} {version}".strip() if credit["licence"] in ("by", "by-sa") else name


def write_data(manifest: dict, order: list[str]) -> list[dict]:
    refs = []
    for pose_id in order:
        result = manifest["poses"].get(pose_id)
        if not result:
            continue
        for ref in result["kept"]:
            credit = credit_of(ref)
            assert credit["licence"] in ALLOWED_LICENCES
            refs.append(
                {
                    "id": f"{pose_id}-{ref['variant']}",
                    "pose": pose_id,
                    "base": ref["base"],
                    "variant": ref["variant"],
                    "aspect": ref["aspect"],
                    "people": [
                        [{"x": round(p["x"], 3), "y": round(p["y"], 3)} if p else None for p in body]
                        for body in ref["people"]
                    ],
                    "credit": credit,
                }
            )
    DATA.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "about": "Reference poses read (DWPose) from openly licensed photos. Generated by "
        "scripts/pose-refs — do not edit by hand. Credits: docs/pose-reference-credits.md",
        "references": refs,
    }
    text = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    # One reference per line keeps diffs readable.
    text = text.replace('},{"id"', '},\n{"id"').replace('"references":[{', '"references":[\n{')
    DATA.write_text(text + "\n")
    return refs


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("[", "\\[").replace("]", "\\]").replace("\n", " ")


def write_credits(refs: list[dict], labels: dict[str, str]) -> None:
    lines = [
        "# Pose reference credits",
        "",
        "Castcut's real-world reference poses (the \"real pose\" variants of Day / Story poses) are",
        "skeletons — joint positions only — read with DWPose from the openly licensed photographs",
        "below. No photo is shipped with the app. Each line names the photo, its creator and its",
        "licence; follow the link for the original. Licences kept: CC0, Public Domain Mark, CC BY",
        "and CC BY-SA (no NonCommercial or NoDerivatives). Generated by `scripts/pose-refs/build.py`.",
        "",
    ]
    current = None
    for ref in refs:
        if ref["pose"] != current:
            current = ref["pose"]
            lines += ["", f"## {labels.get(current, current)} (`{current}`)", ""]
        c = ref["credit"]
        creator = md_escape(c["creator"])
        creator = f"[{creator}](<{c['creatorUrl']}>)" if c.get("creatorUrl") else creator
        lines.append(
            f"- {ref['variant']}. [{md_escape(c['title'])}](<{c['source']}>) by {creator}, "
            f"[{licence_label(c)}](<{c['licenceUrl']}>) — via {c['provider']}"
        )
    CREDITS.write_text("\n".join(lines).replace("\n\n\n", "\n\n") + "\n")


def draw_skeleton(img: np.ndarray, bodies: list) -> None:
    h, w = img.shape[:2]
    thick = max(2, int(round(min(h, w) / 90)))
    for body in bodies:
        for (a, b), colour in zip(LIMBS, COLOURS):
            pa, pb = body[a], body[b]
            if pa and pb:
                cv2.line(img, (int(pa["x"] * w), int(pa["y"] * h)), (int(pb["x"] * w), int(pb["y"] * h)),
                         colour, thick, cv2.LINE_AA)
        for p in body:
            if p:
                cv2.circle(img, (int(p["x"] * w), int(p["y"] * h)), thick + 1, (255, 255, 255), -1, cv2.LINE_AA)


def contact_sheets(manifest: dict, order: list[str], labels: dict[str, str]) -> list[Path]:
    out = CACHE / "sheets"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("sheet-*.jpg"):
        old.unlink()
    tile_h, label_w, per_sheet = 230, 190, 12
    rows = [pid for pid in order if pid in manifest["poses"]]
    paths = []
    for start in range(0, len(rows), per_sheet):
        chunk = rows[start:start + per_sheet]
        row_imgs = []
        for pid in chunk:
            tiles = []
            for ref in manifest["poses"][pid]["kept"]:
                img = cv2.imread(str(CACHE / ref["cropFile"]))
                if img is None:
                    continue
                scale = tile_h / img.shape[0]
                img = cv2.resize(img, (max(1, int(img.shape[1] * scale)), tile_h), interpolation=cv2.INTER_AREA)
                draw_skeleton(img, ref["people"])
                cv2.putText(img, f"{ref['variant']} {ref['photo']['licence']}", (4, 18),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 3, cv2.LINE_AA)
                cv2.putText(img, f"{ref['variant']} {ref['photo']['licence']}", (4, 18),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
                tiles += [img, np.full((tile_h, 6, 3), 255, np.uint8)]
            label = np.full((tile_h, label_w, 3), 255, np.uint8)
            result = manifest["poses"][pid]
            for i, text in enumerate([pid, labels.get(pid, ""), f"kept {len(result['kept'])}"]):
                cv2.putText(label, text[:24], (6, 30 + 26 * i), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 0, 0), 1, cv2.LINE_AA)
            row = np.hstack([label, *tiles]) if tiles else label
            row_imgs.append(row)
        width = max(r.shape[1] for r in row_imgs)
        padded = [np.hstack([r, np.full((r.shape[0], width - r.shape[1], 3), 255, np.uint8)]) for r in row_imgs]
        sheet = np.vstack([np.vstack([r, np.full((6, width, 3), 200, np.uint8)]) for r in padded])
        path = out / f"sheet-{start // per_sheet + 1:02d}.jpg"
        cv2.imwrite(str(path), sheet, [cv2.IMWRITE_JPEG_QUALITY, 85])
        paths.append(path)
    return paths


def report(manifest: dict, order: list[str]) -> str:
    lines = ["pose                 kept searched tried  rejected by reason"]
    for pid in order:
        r = manifest["poses"].get(pid)
        if not r:
            continue
        reasons = ", ".join(f"{k} {v}" for k, v in sorted(r["rejected"].items(), key=lambda kv: -kv[1]))
        lines.append(f"{pid:<20} {len(r['kept']):>4} {r['searched']:>8} {r['tried']:>5}  {reasons}")
    empty = [pid for pid in order if pid in manifest["poses"] and not manifest["poses"][pid]["kept"]]
    lines += ["", f"no references: {', '.join(empty) or 'none'}"]
    return "\n".join(lines)


def main() -> None:
    manifest = json.loads((CACHE / "manifest.json").read_text())
    poses = json.loads((CACHE / "poses.json").read_text()) if (CACHE / "poses.json").exists() else []
    order = [p["id"] for p in poses] or list(manifest["poses"])
    labels = {p["id"]: p["label"] for p in poses}
    refs = write_data(manifest, order)
    write_credits(refs, labels)
    sheets = contact_sheets(manifest, order, labels)
    text = report(manifest, order)
    (CACHE / "report.txt").write_text(text + "\n")
    print(text)
    print(f"\n{len(refs)} references → {DATA.relative_to(ROOT)} ({DATA.stat().st_size // 1024} KB)")
    print("sheets: " + ", ".join(str(p) for p in sheets))


if __name__ == "__main__":
    main()
