// Generated by scripts/gen-classic-app.mts from src/app/api/gallery/vision-review/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 120;
export * from '@/app/api/gallery/vision-review/route';
