// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/castcut-nodes/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 180;
export * from '@/app/api/comfyui/castcut-nodes/route';
