// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/input-folder/delete/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 300;
export * from '@/app/api/comfyui/input-folder/delete/route';
