// Generated by scripts/gen-classic-app.mts from src/app/plugins/nsfw-generator/page.tsx — do not edit.
export * from '@/app/plugins/nsfw-generator/page';
export { default } from '@/app/plugins/nsfw-generator/page';
