// Generated by scripts/gen-classic-app.mts from src/app/api/gallery/media/persist/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 60;
export * from '@/app/api/gallery/media/persist/route';
