// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/manager/install/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 120;
export * from '@/app/api/comfyui/manager/install/route';
