// Generated by scripts/gen-classic-app.mts from src/app/api/plugin-hooks/denoise-rewrite/route.ts — do not edit.
export const runtime = 'nodejs';
export * from '@/app/api/plugin-hooks/denoise-rewrite/route';
