// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/editor-workflows/route.ts — do not edit.
export const runtime = 'nodejs';
export * from '@/app/api/comfyui/editor-workflows/route';
