// Generated by scripts/gen-classic-app.mts from src/studio-app/controlnet/page.tsx — do not edit.
export * from '@/studio-app/controlnet/page';
export { default } from '@/studio-app/controlnet/page';
